
### Create a new document
POST https://dmit2015-1222-valer11-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "buy a large coffe",
  "important": true
}

### Create a new document
POST https://dmit2015-1222-valer11-demos-default-rtdb.firebaseio.com/Todo.json
Content-Type: application/json

{
  "task": "go home and sleep",
  "important": false
}

### GET All documents
GET https://dmit2015-1222-valer11-demos-default-rtdb.firebaseio.com/Todo.json

### GET One document by key
GET https://dmit2015-1222-valer11-demos-default-rtdb.firebaseio.com/Todo/primaryKeyValue.json

### UPDATE document - will replace all properties with the properties in the request body - if you miss a property it will be removed
PUT https://dmit2015-1222-valer11-demos-default-rtdb.firebaseio.com/Todo/primaryKeyValue.json
Content-Type: application/json

{
  "task": "drink coffee",
  "important": true
}

### DELETE document - use this if you want to delete a document
DELETE https://dmit2015-1222-valer11-demos-default-rtdb.firebaseio.com/Todo/primaryKeyValue.json


### PATCH document - use this if you want to update some of the properties but not all of them
PATCH https://dmit2015-1222-valer11-demos-default-rtdb.firebaseio.com/Todo/primaryKeyValue.json
Content-Type: application/json

{
  "propertyName": "propertyValue"
}